# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYwtWD2EsnfOvYQVL3bE9JhxwCYhwfJz
"""

def kasallik_tashxisi(belgi):
  if belgi == "isitma":
      return "Kyupen iching"
  elif belgi== "Bosh og'rig'i":
      return "Trimol iching"
  elif belgi== "Tish og'rig'i":
      return "Sinepar iching"
  else:
      return "Shifokorga murojaat qiling!"
belgi = input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)

print(natija)

def kitob_tavsiyasi(belgi):
  if belgi == "Detektiv":
    return "Sherlok Holms"
  elif belgi== "Dramatik janr":
    return "Jinoyat va jazo"
  elif belgi== "Motivatsion":
    return "O'yla va boy bo'l"
  elif belgi=="Psixologik":
    return "Manipulyatsiya siri"
  elif belgi=="Talabalar uchun":
    return "Talaba do'stimga 78+ tavsiya"
  elif belgi=="Siyosat":
    return"Shahzoda"
  elif belgi== "Bolalar uchun":
    return "ertaklar"
  elif belgi=="Kattalar uchun":
    return "1984"
  elif belgi== "Mafiya olami":
    return "Qashqirlar makoni"
  elif belgi== "Ayollar uchun":
    return "Ayollarga eslatma"

  else:
    return "Kitob do'koniga boring"
belgi== input("Kitob janrini tanlang")
natija=kitob_tavsiyasi(belgi)
print(natija)